### ISSUE TITLE
Files die met een . beginnen, mogen niet gesynct worden

### ISSUE THREAD

**Issue by bramschulting** [IDH14/protocol#3]
Op Mac wordt bijvoorbeeld een `.DS_Store` file gemaakt met metadata over de directory waar hij in staat (volgens mij?). Die files moeten we denk ik niet syncen.

**Comment by ghost** [comment]
Bepaalt de client dat niet? M.a.w. dat lijkt me geen issue voor het protocol. Meer een lokale instelling die je op je client moet kunnen maken. Anders krijg je nl. een server die op de hoogte moet zijn van alle bestaande OS-quirks.

**Comment by bramschulting** [comment]
En als een client dit niet goed implementeert? Dan worden al die files via de server alsnog naar alle clients gestuurd. Het lijkt mij handig om dit op te nemen in het protocol.

**Comment by ghost** [comment]
Er zijn wel meer fouten die een client kan maken die direct gevolgen hebben voor alle andere clients. Ik snap je gedachtengang wel, maar ik denk niet dat het de verantwoordelijkheid van de server is. Bovendien krijg je op Windows een probleem, omdat het wel/niet zichtbaar zijn van een bestand met bestandsattributen wordt geregeld en niet persé uit de naam (beginnend met een . zoals bij Unix-achtigen) blijkt. Met andere woorden, dan moet de client toch zelf gaan selecteren.

Het lijkt me hoe dan ook een issue dat we later wel kunnen adresseren in een volgende iteratie. Wat vinden de anderen?

**Comment by perryfaro** [comment]
ik zou het bestand wel gewoon overzetten in de gedachte van keep it simple. Anders moeten we we gaan kijken welke bestanden er nog meer er niet worden overgezet mogen worden.

Eventueel kun je in de client bepalen dat het wel of niet wordt gesynct.

**Comment by Mvanbale** [comment]
Als men met een regex kan instellen wat de client wel/niet wilt syncen lijkt me dat voldoende. Lijkt me idd niet echt iets voor in het protocol zelf.
